/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/hasan/Downloads/helmet.glb -t -T 
Files: /Users/hasan/Downloads/helmet.glb [10.64MB] > /Users/hasan/repos/landing-playground/app/components/helmet-transformed.glb [1.8MB] (83%)
*/

import * as THREE from "three";
import React, { JSX, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Egyptian_1: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
  animations: [];
};

export function Model({
  isHovered,
  globalPointer,
  ...props
}: JSX.IntrinsicElements["group"] & {
  isHovered: boolean;
  globalPointer: { x: number; y: number };
}) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/helmet-transformed.glb") as
    | GLTFResult
    | any;
  const { lerp } = THREE.MathUtils;

  useFrame((state) => {
    if (!group.current) return;
    const t = state.clock.getElapsedTime();
    const { position, rotation } = group.current;

    position.z = THREE.MathUtils.lerp(position.z, 0, 0.2);

    // 1. Floating Animation (Up and Down)
    position.y = lerp(
      position.y,
      Math.sin(t / 0.8) / 10, // Moves up/down by 0.1 units
      0.1,
    );

    // default target rotation
    let targetX = -0.3;
    let targetY = 0.3;

    if (isHovered) {
      // 2. Rotate towards pointer
      targetX = Math.min(-globalPointer.y * 0.5, 0.3);
      targetY = globalPointer.x * 0.8 + 0.3;
    }

    rotation.x = lerp(rotation.x, targetX, 0.1);
    rotation.y = lerp(rotation.y, targetY, 0.1);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Egyptian_1.geometry}
        material={materials["Material.002"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.771}
      />
    </group>
  );
}

useGLTF.preload("/helmet-transformed.glb");
